/** Локальные ассеты из `public/assets/` — расширения соответствуют реальному формату файлов. */
export const ASSETS = {
  avatar: "/assets/avatar.jpg",
  backArrow: "/assets/back-arrow.svg",
  tabBefore: "/assets/tab-before.svg",
  tabAfter: "/assets/tab-after.svg",
  tabBeforeInactive: "/assets/tab-before-inactive.svg",
  tabAfterInactive: "/assets/tab-after-inactive.svg",
  iconSun: "/assets/icon-sun.svg",
  iconBell: "/assets/icon-bell.svg",
  iconPlane: "/assets/icon-plane.svg",
  tagEmpty: "/assets/tag-empty.svg",
  svcMask16: "/assets/svc-mask-16.svg",
  aliceFill: "/assets/alice-fill.svg",
  yandexYa: "/assets/yandex-ya.svg",
  spaceLogoMask: "/assets/space-logo-mask.svg",
  spaceLogoMark: "/assets/space-logo-mark.svg",
  spaceLogoWordmark: "/assets/space-logo-wordmark.svg",
  trashIcon: "/assets/trash-icon.svg",
  generatingIllustration1: "/assets/generating-illustration-1.svg",
  generatingIllustration2: "/assets/generating-illustration-2.svg",
  generatingSpinner: "/assets/generating-spinner.svg",
  generatingSpinnerDot: "/assets/generating-spinner-dot.svg",
  maskEdit: "/assets/mask-edit.svg",
  perfPlus: "/assets/perf-plus.svg",
  perfPlusPlus: "/assets/perf-plus-plus.svg",
  maskDownload: "/assets/mask-download.svg",
  maskPlus: "/assets/mask-plus.svg",
} as const;
